baseURL = 'https://example.org/'
title = 'My New Hugo Site'
contentDir = 'content'

defaultContentLanguage = "pl"
[languages]
[languages.pl]
  languageName = "Polski"
  weight = 1

[languages.en]
  languageName = "English"
  weight = 2