baseURL = 'https://osedax.pl/'
title = 'Osedax'
defaultContentLanguage = "pl"

[languages]
[languages.pl]
  languageName = "Polski"
  weight = 1

[languages.en]
  languageName = "English"
  weight = 2